### PR TITLE
"200-flexdashboard-render-text" shinytest fixes

### PR DESCRIPTION
**Pull request by MadhulikaTanuboddi**
Add wait on Page 2 of flexdashboard to make sure month is updated

This is a potential fix especially for Windows builds on GHA

### CODE REVIEW

**Review by MadhulikaTanuboddi — COMMENTED** [review]
Thank you (sorry, was an accidental commit for these files)

**Review by schloerke — APPROVED** [review]
Went through the test changes again. It is just the SHA changing randomly.

While this causes the tests to fail, this is no worse than the prior SHA changing before. It'll be a false-positive that we should note.

@MadhulikaTanuboddi Feel free to squash/merge when you're ready. 😃

**Comment by schloerke** [comment]
With https://github.com/rstudio/rmarkdown/pull/2137 merged into rmarkdown devel, we should be able to get a green check within two passes (one to update the sha, the second to get a green check)

**Comment by schloerke** [comment]
Failures now are only shinyjster failures. These will be fixed later. Merging!

**Pull request merged**
